;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((rust-mode . ((lsp-rust-analyzer-linked-projects . ["./chapter-1/hello_cargo/Cargo.toml"
                                                     "./chapter-2/guessing_game/Cargo.toml"
                                                     "./chapter-3/variables/Cargo.toml"
                                                     "./chapter-3/data_types/Cargo.toml"
                                                     "./chapter-3/functions/Cargo.toml"
                                                     "./chapter-3/control_flow/Cargo.toml"
                                                     "./chapter-4/ownership/Cargo.toml"
                                                     "./chapter-4/references_and_borrowing/Cargo.toml"
                                                     "./chapter-4/slice/Cargo.toml"
                                                     "./chapter-5/structs/Cargo.toml"
                                                     "./chapter-5/rectangles/Cargo.toml"
                                                     "./chapter-6/enums/Cargo.toml"
                                                     "./chapter-6/matches/Cargo.toml"
                                                     "./chapter-6/if-let/Cargo.toml"
                                                     "./chapter-7/my-project/Cargo.toml"
                                                     "./chapter-7/backyard/Cargo.toml"
                                                     "./chapter-7/restaurant/Cargo.toml"
                                                     "./chapter-7/use-practice/Cargo.toml"
                                                     "./chapter-8/vectors/Cargo.toml"
                                                     "./chapter-8/strings/Cargo.toml"
                                                     "./chapter-8/hashmaps/Cargo.toml"
                                                     "./chapter-9/panic/Cargo.toml"
                                                     "./chapter-9/error-handling/Cargo.toml"
                                                     "./chapter-9/to-panic-or-not/Cargo.toml"
                                                     "./chapter-10/generics/Cargo.toml"
                                                     "./chapter-10/traits/Cargo.toml"
                                                     "./chapter-10/lifetimes/Cargo.toml"
                                                     "./chapter-11/adder/Cargo.toml"
                                                     "./chapter-11/silly-function/Cargo.toml"]))))
