[package]
name = "panic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# abort instead of unwind will leave it up to the OS to clean memory on panic!
panic = 'abort'

[dependencies]
